(()=>{'use strict';
const AVATARS=['🦊','🐼','🐯','🦁','🐸','🐨','🐰','🐵'];
const COLORS=['#ff6b6b','#4dabf7','#51cf66','#ffd43b','#b197fc','#ff922b','#22b8cf','#f06595'];
const $=id=>document.getElementById(id);
function injectStyles(){const s=document.createElement('style');s.textContent=`
.profileSetup{margin:12px 0 16px;padding:12px;border:1px solid #31538f;border-radius:16px;background:#091938;text-align:left}.profileLabel{font-size:12px;color:#9fb0d4;margin:8px 0 6px}.avatarChoices,.colorChoices{display:flex;gap:8px;flex-wrap:wrap}.avatarChoice,.colorChoice{width:42px;height:42px;border-radius:12px;border:2px solid transparent;background:#102653;display:flex;align-items:center;justify-content:center;font-size:24px;cursor:pointer}.avatarChoice.selected,.colorChoice.selected{border-color:#fff;transform:scale(1.08)}.colorChoice{font-size:0}.playerCard{position:relative;overflow:hidden;padding-left:58px!important;min-height:66px}.playerAvatar{position:absolute;left:10px;top:50%;transform:translateY(-50%);width:38px;height:38px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:24px;background:#081633;border:2px solid var(--pc,#31538f);box-shadow:0 0 16px color-mix(in srgb,var(--pc,#31538f) 45%,transparent)}.playerCard.active{box-shadow:0 0 0 2px var(--pc,#ffd44d),0 0 22px color-mix(in srgb,var(--pc,#ffd44d) 35%,transparent)}.answerFX{position:fixed;inset:0;z-index:9999;pointer-events:none;display:flex;align-items:center;justify-content:center;opacity:0}.answerFX.show{animation:fxIn .95s ease forwards}.answerFX.correct{background:radial-gradient(circle,#2dd66f55,transparent 60%)}.answerFX.wrong{background:radial-gradient(circle,#ff5a6866,transparent 65%)}.answerFXText{font-size:clamp(52px,14vw,110px);font-weight:1000;text-align:center;text-shadow:0 8px 28px #000;transform:scale(.6)}.answerFX.correct .answerFXText{color:#73ff9f}.answerFX.wrong .answerFXText{color:#ff7a85}@keyframes fxIn{0%{opacity:0}15%{opacity:1}70%{opacity:1}100%{opacity:0}}@keyframes popText{0%{transform:scale(.55)}55%{transform:scale(1.15)}100%{transform:scale(1)}}.answerFX.show .answerFXText{animation:popText .45s ease forwards}.miniConfetti{position:fixed;top:-20px;width:10px;height:18px;z-index:10000;pointer-events:none;animation:fallV12 1.6s linear forwards}@keyframes fallV12{to{transform:translateY(110vh) rotate(600deg)}}body.wrongShake{animation:wrongShake .35s ease}@keyframes wrongShake{0%,100%{transform:translateX(0)}25%{transform:translateX(-7px)}50%{transform:translateX(7px)}75%{transform:translateX(-4px)}}`;
document.head.appendChild(s)}
function addProfileControls(inputId,prefix){const input=$(inputId);if(!input||input.dataset.profileReady)return;input.dataset.profileReady='1';let avatar=Number(localStorage.getItem(prefix+'Avatar')||0)%AVATARS.length,color=Number(localStorage.getItem(prefix+'Color')||0)%COLORS.length;const box=document.createElement('div');box.className='profileSetup';box.innerHTML='<div class="profileLabel">Аватар</div><div class="avatarChoices"></div><div class="profileLabel">Цвет игрока</div><div class="colorChoices"></div>';const av=box.querySelector('.avatarChoices'),co=box.querySelector('.colorChoices');AVATARS.forEach((x,i)=>{const b=document.createElement('button');b.type='button';b.className='avatarChoice'+(i===avatar?' selected':'');b.textContent=x;b.onclick=()=>{avatar=i;localStorage.setItem(prefix+'Avatar',i);[...av.children].forEach(y=>y.classList.remove('selected'));b.classList.add('selected')};av.appendChild(b)});COLORS.forEach((x,i)=>{const b=document.createElement('button');b.type='button';b.className='colorChoice'+(i===color?' selected':'');b.style.background=x;b.onclick=()=>{color=i;localStorage.setItem(prefix+'Color',i);[...co.children].forEach(y=>y.classList.remove('selected'));b.classList.add('selected')};co.appendChild(b)});input.insertAdjacentElement('afterend',box);input.dataset.getProfile=prefix}
function encodeInput(input){if(!input||input.dataset.encoded==='1')return;const prefix=input.dataset.getProfile||'p';const a=Number(localStorage.getItem(prefix+'Avatar')||0)%8,c=Number(localStorage.getItem(prefix+'Color')||0)%8;let n=input.value.trim().replace(/^§\d\d/,'');if(n)input.value='§'+a+c+n;input.dataset.encoded='1'}
function decodeName(raw){const m=String(raw||'').match(/^§([0-7])([0-7])(.*)$/);return m?{avatar:+m[1],color:+m[2],name:m[3]}:{avatar:0,color:0,name:String(raw||'')}}
function enhanceCards(){document.querySelectorAll('.playerCard').forEach(card=>{const b=card.querySelector('b');if(!b)return;const d=decodeName(b.textContent);if(b.dataset.decoded!==d.name){b.textContent=d.name;b.dataset.decoded=d.name}card.style.setProperty('--pc',COLORS[d.color]);let a=card.querySelector('.playerAvatar');if(!a){a=document.createElement('div');a.className='playerAvatar';card.prepend(a)}a.textContent=AVATARS[d.avatar]})}
function cleanMessages(){['turnInfo','answerMsg','winnerName'].forEach(id=>{const e=$(id);if(!e)return;let t=e.textContent;const r=t.replace(/§[0-7][0-7]([^\s]+)/g,'$1');if(r!==t)e.textContent=r})}
let lastMsg='';function fx(type,text){let layer=document.querySelector('.answerFX');if(!layer){layer=document.createElement('div');layer.className='answerFX';layer.innerHTML='<div class="answerFXText"></div>';document.body.appendChild(layer)}layer.className='answerFX '+type;layer.querySelector('.answerFXText').innerHTML=text;void layer.offsetWidth;layer.classList.add('show');setTimeout(()=>layer.classList.remove('show'),1000);if(type==='correct'){for(let i=0;i<34;i++){const c=document.createElement('i');c.className='miniConfetti';c.style.left=Math.random()*100+'vw';c.style.background=COLORS[i%COLORS.length];c.style.animationDelay=Math.random()*.25+'s';document.body.appendChild(c);setTimeout(()=>c.remove(),2100)}}else{document.body.classList.remove('wrongShake');void document.body.offsetWidth;document.body.classList.add('wrongShake');setTimeout(()=>document.body.classList.remove('wrongShake'),400)}}
function watchFeedback(){const e=$('answerMsg');if(!e)return;const t=e.textContent.trim();if(!t||t===lastMsg)return;lastMsg=t;if(/^Правильно!/.test(t)){const m=t.match(/\+(\d+)/);fx('correct','ПРАВИЛЬНО!'+(m?'<br><span style="font-size:.65em">+'+m[1]+'</span>':''))}else if(/^Неверно/.test(t)){const m=t.match(/−(\d+)|-(\d+)/);fx('wrong','НЕВЕРНО'+(m?'<br><span style="font-size:.65em">−'+(m[1]||m[2])+'</span>':''))}else if(/ответил правильно/.test(t)){fx('correct','ПРАВИЛЬНО!')}}
function patchShare(){const e=$('shareLink');if(e&&e.textContent)e.textContent=e.textContent.replace(/([?&])v=11(&|$)/,'$1v=12$2')}
function init(){injectStyles();addProfileControls('creatorName','creator');addProfileControls('joinName','guest');const c=$('createBtn'),j=$('connectBtn');if(c)c.addEventListener('click',()=>encodeInput($('creatorName')),true);if(j)j.addEventListener('click',()=>encodeInput($('joinName')),true);new MutationObserver(()=>{enhanceCards();cleanMessages();watchFeedback();patchShare()}).observe(document.body,{subtree:true,childList:true,characterData:true});enhanceCards();const ns=$('netStatus');if(ns)ns.textContent='Supabase Realtime v12';const tiny=document.querySelector('#home .tiny');if(tiny)tiny.textContent='Мультиплеерная викторина · Realtime v12'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();